<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20240314160308" tests="1" file="unittest/loader.py" time="0.002" timestamp="2024-03-14T16:03:08" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="helloworld_tests" time="0.002" timestamp="2024-03-14T16:03:08">
		<error type="ImportError" message="Failed to import test module: helloworld_tests
Traceback (most recent call last):
  File &quot;/Users/bharatkondam/opt/anaconda3/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/bharatkondam/pyb/src/unittest/python/helloworld_tests.py&quot;, line 3, in &lt;module&gt;
    from main.python.helloworld import helloworld
ModuleNotFoundError: No module named 'main'
"><![CDATA[Traceback (most recent call last):
  File "/Users/bharatkondam/opt/anaconda3/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/bharatkondam/opt/anaconda3/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Users/bharatkondam/opt/anaconda3/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/bharatkondam/opt/anaconda3/lib/python3.9/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: helloworld_tests
Traceback (most recent call last):
  File "/Users/bharatkondam/opt/anaconda3/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/bharatkondam/pyb/src/unittest/python/helloworld_tests.py", line 3, in <module>
    from main.python.helloworld import helloworld
ModuleNotFoundError: No module named 'main'

]]></error>
	</testcase>
</testsuite>
